"""House style, enforced rather than remembered.

The prior project carried the same two rules and the same test. The forbidden
tokens are built from codepoints rather than written out, so this file does not
fail on its own patterns.
"""
from __future__ import annotations

import pytest

from colophon.paths import REPO

SKIP_DIRS = {".git", "_cache", "__pycache__", ".pytest_cache", "env"}
CHECKED = (".py", ".md", ".cff", ".toml", ".yml", ".yaml")

# Verbatim records of documents this project did not write. Their house style is
# not ours to enforce, and altering them would break them as records.
VERBATIM = {"COLOPHON_BRIEF.md"}

EM_DASH = chr(0x2014)
MISCASED_VENDOR = ("A" + "ycan", "AY" + "CAN", "Ay" + "Can")


def _files():
    for path in REPO.rglob("*"):
        if not path.is_file() or path.suffix not in CHECKED:
            continue
        if any(part in SKIP_DIRS for part in path.parts):
            continue
        if path.name in VERBATIM:
            continue
        yield path


@pytest.mark.parametrize("path", sorted(_files(), key=str))
def test_no_em_dashes(path):
    text = path.read_text(encoding="utf-8", errors="replace")
    for n, line in enumerate(text.splitlines(), 1):
        assert EM_DASH not in line, "%s:%d contains an em-dash" % (path.name, n)


@pytest.mark.parametrize("path", sorted(_files(), key=str))
def test_aycan_is_lowercase(path):
    text = path.read_text(encoding="utf-8", errors="replace")
    for n, line in enumerate(text.splitlines(), 1):
        for token in MISCASED_VENDOR:
            assert token not in line, (
                "%s:%d writes %s, which is always lowercase" % (path.name, n, token))


def test_the_verbatim_exemption_is_narrow():
    """A widening exemption list is how a style rule stops being a rule."""
    assert VERBATIM == {"COLOPHON_BRIEF.md"}
    for name in VERBATIM:
        assert (REPO / name).exists(), "%s is exempted but does not exist" % name


def test_results_write_ups_are_generated_not_typed():
    """Every markdown file in results/ has to be emitted by code, so a number
    cannot drift out of agreement with the table it came from. The exceptions
    are declarations about the project rather than measurements."""
    emitters = {
        "phase0_census.md": "colophon/index.py",
        "claim3_provenance.md": "colophon/provenance.py",
        "prior_art.md": "colophon/prior_art.py",
        "prisma_s_appendix.md": "colophon/prisma.py",
        "table1_writers.md": "colophon/writers.py",
        "floor_overlap.md": "colophon/floor.py",
        "phase1_variants.md": "colophon/variants.py",
        "phase2_pilot.md": "colophon/fetch.py",
        "phase2_census.md": "colophon/census.py",
        "phase2_gsps_dcmpschk.md": "colophon/gsps_dcmpschk.py",
        "claims_map.md": "colophon/claims_map.py",
        "pre06_sampling_frame.md": "colophon/sample.py",
        "phase3_segmentation.md": "colophon/phase3_report.py",
        "ihe_air_table.md": "colophon/standards.py",
    }
    hand_written = {"ai_use.md", "README.md", "prior_art_recheck.md"}
    for path in (REPO / "results").glob("*.md"):
        assert path.name in emitters or path.name in hand_written, (
            "%s is neither generated by a named module nor a declared "
            "hand-written file" % path.name)
    for name, module in emitters.items():
        source = (REPO / module).read_text(encoding="utf-8")
        assert name in source, "%s does not write %s" % (module, name)


# Adjudication write-ups live one directory down, outside the glob above, and
# each is emitted by the Track C module that computes its numbers. Registering
# them here is what keeps a hand-typed rate out of results/phase2/.
PHASE2_EMITTERS = {
    "net_rates_rwv_kos.md": "colophon/adjudicate_rwv_kos.py",
    "net_rates_gsps.md": "colophon/adjudicate_gsps.py",
    "net_rates_parametric_map.md": "colophon/adjudicate_pm.py",
    "net_rates_comprehensive_sr.md": "colophon/adjudicate_csr.py",
    "net_rates_comprehensive_3d_sr.md": "colophon/adjudicate_c3dsr.py",
}


def test_phase2_adjudications_are_generated_not_typed():
    """Same rule as the results/ write-ups, applied to results/phase2/."""
    phase2 = REPO / "results" / "phase2"
    if not phase2.exists():
        return
    for path in phase2.glob("net_rates_*.md"):
        assert path.name in PHASE2_EMITTERS, (
            "%s is not generated by a named module" % path.name)
    for name, module in PHASE2_EMITTERS.items():
        source = (REPO / module).read_text(encoding="utf-8")
        assert name in source, "%s does not write %s" % (module, name)
