"""The citation guard.

The manuscript was drafted with citations as bare author surnames and no
bibliography. That is the state in which a citation quietly stops pointing at
anything: a surname is not checkable, and a reader cannot tell a resolved claim
from a remembered one.

This module makes the reference set a checked artefact rather than a typed list.
It reads `results/manuscript/references.md`, reads the bracketed markers in the
hand-written manuscript documents, and reports four things a reviewer would
otherwise have to establish by hand:

1. every bracketed marker in the text resolves to an entry;
2. every entry is cited at least once, so the list carries no padding;
3. every entry carries a resolvable identifier, a DOI, an arXiv id or a URL;
4. no bare surname citation is left in the text.

Two further checks are against pinned artefacts rather than against the text,
because both are facts about documents this project did not write:

5. the six Correction Proposals and Supplement 243 are stated with the title,
   status and edition the DICOM status table carries, read from
   `results/cp/dicom_status_rows.json` rather than from memory;
6. the IHE AIR quotation in the Discussion is present at the revision and printed
   page the Discussion names, checked against the pinned PDF offline.

Nothing here fetches. The status table and the AIR PDF are both on disk.

Reproduce with `python -m colophon.citations`.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from .paths import RESULTS, REPO

MANUSCRIPT = RESULTS / "manuscript"
REFERENCES = MANUSCRIPT / "references.md"
STATUS_ROWS = RESULTS / "cp" / "dicom_status_rows.json"
AIR_PDF = REPO / "_cache" / "air" / "IHE_RAD_Suppl_AIR_Rev1-3_TI_2025-08-08.pdf"
OUT = MANUSCRIPT / "citation_check.json"

# Hand-written documents that carry citations. `tables.md` is generated by
# colophon.manuscript_tables and is deliberately outside this set: a citation
# marker typed into a generated file would be erased by the next run.
CITING_DOCS = ("abstract.md", "abstract_venue.md", "introduction.md",
               "methods.md", "results.md", "discussion.md", "figures.md",
               "front_matter.md")

ENTRY = re.compile(r"^(\d+)\.\s+(.*)$")
MARKER = re.compile(r"\[(\d+(?:\s*,\s*\d+)*)\]")
IDENTIFIER = re.compile(r"doi:10\.\d{4,9}/|arXiv:\d{4}\.\d{4,5}|https?://")

# A surname followed by "et al" with no bracketed marker close behind is the
# state this module exists to detect. The pair form has no general pattern that
# is not also matched by ordinary prose, so the pairs actually used are named.
ET_AL = re.compile(r"\b([A-Z][A-Za-z]+)\s+et\s+al\b")
SURNAME_PAIRS = ("Bennett and Smith",)
RFC = re.compile(r"\bRFC\s+(\d+)\b")
# How far after a citation a marker may sit and still be its marker. Long enough
# to survive a line wrap between the name and the bracket, short enough that the
# next sentence's marker cannot be mistaken for this one's.
LOOKAHEAD = 40


def _read(name: str) -> str:
    path = MANUSCRIPT / name
    return path.read_text(encoding="utf-8") if path.exists() else ""


def entries(text: str | None = None) -> dict[int, str]:
    """Reference number to entry text, from references.md.

    An entry runs from its numbered line to the next numbered line or heading,
    so a wrapped entry is read whole and a truncated one is visible as such.
    """
    text = REFERENCES.read_text(encoding="utf-8") if text is None else text
    out: dict[int, str] = {}
    current: int | None = None
    for line in text.splitlines():
        m = ENTRY.match(line)
        if m:
            current = int(m.group(1))
            out[current] = m.group(2).strip()
            continue
        if line.startswith("#"):
            current = None
            continue
        if current is not None and line.strip():
            out[current] += " " + line.strip()
    return out


def cited() -> dict[int, list[str]]:
    """Reference number to the documents that cite it."""
    out: dict[int, list[str]] = {}
    for name in CITING_DOCS:
        for group in MARKER.findall(_read(name)):
            for token in group.split(","):
                n = int(token.strip())
                out.setdefault(n, [])
                if name not in out[n]:
                    out[n].append(name)
    return out


def bare_citations() -> list[dict]:
    """Every citation in the text that no bracketed marker follows."""
    found = []
    for name in CITING_DOCS:
        text = _read(name)
        for m in ET_AL.finditer(text):
            tail = text[m.end():m.end() + LOOKAHEAD]
            if not MARKER.search(tail):
                found.append({"file": name, "kind": "et al",
                              "text": m.group(0),
                              "context": _context(text, m.start())})
        for pair in SURNAME_PAIRS:
            start = 0
            while True:
                i = text.find(pair, start)
                if i < 0:
                    break
                start = i + len(pair)
                if not MARKER.search(text[start:start + LOOKAHEAD]):
                    found.append({"file": name, "kind": "surname pair",
                                  "text": pair,
                                  "context": _context(text, i)})
        for m in RFC.finditer(text):
            if not MARKER.search(text[m.end():m.end() + LOOKAHEAD]):
                found.append({"file": name, "kind": "RFC",
                              "text": m.group(0),
                              "context": _context(text, m.start())})
    return found


def _context(text: str, at: int, width: int = 70) -> str:
    lo = max(0, at - width // 2)
    return " ".join(text[lo:at + width].split())


def unresolvable() -> list[int]:
    """Entries carrying no DOI, arXiv id or URL."""
    return sorted(n for n, e in entries().items() if not IDENTIFIER.search(e))


def numbering() -> dict:
    nums = sorted(entries())
    expected = list(range(1, len(nums) + 1))
    return {"count": len(nums), "contiguous_from_one": nums == expected,
            "missing": sorted(set(expected) - set(nums)),
            "duplicated": []}


def standards_rows_agree() -> list[str]:
    """The CP and Supplement entries against the pinned DICOM status table.

    A status and an edition are facts about somebody else's document, and the
    failure mode is quoting one from memory. Each is checked against the row as
    it was retrieved, which is on disk with the page's sha256 beside it.
    """
    if not STATUS_ROWS.exists():
        return ["results/cp/dicom_status_rows.json is absent"]
    pinned = json.loads(STATUS_ROWS.read_text(encoding="utf-8"))
    text = REFERENCES.read_text(encoding="utf-8")
    flat = " ".join(text.split())
    problems = []
    for key, row in sorted(pinned["correction_proposals"].items()):
        if key not in flat:
            problems.append("%s is not cited in references.md" % key)
            continue
        if row["title"] not in flat:
            problems.append("%s title differs from the pinned row: %s"
                            % (key, row["title"]))
        if ("edition %s" % row["applies_to"]) not in flat:
            problems.append("%s does not state edition %s"
                            % (key, row["applies_to"]))
    for key, row in sorted(pinned["supplements"].items()):
        if key not in flat:
            problems.append("%s is not cited in references.md" % key)
            continue
        if ("edition %s" % row["applies_to"]) not in flat:
            problems.append("%s does not state edition %s"
                            % (key, row["applies_to"]))
    return problems


AIR_QUOTE = ("Many deployment models involve the AI Models being "
             "separate from the Evidence Creator")


def air_quotation() -> dict:
    """The Discussion's AIR quotation, against the pinned PDF, offline.

    The drafted text cited Rev 1.2 at page 16. The pinned document is Rev 1.3
    and the passage is on printed page 17, so both the revision and the page
    were wrong and both are checked here rather than left to a reader.
    """
    out = {"pdf": str(AIR_PDF), "available": AIR_PDF.exists(),
           "quote_found": False, "printed_page": None, "revision": None}
    if not AIR_PDF.exists():
        return out
    try:
        from pypdf import PdfReader
    except Exception as exc:                      # pragma: no cover
        out["error"] = "pypdf unavailable: %s" % exc
        return out
    reader = PdfReader(str(AIR_PDF))
    for page in reader.pages:
        text = (page.extract_text() or "").replace("​", "")
        if AIR_QUOTE not in " ".join(text.split()):
            continue
        out["quote_found"] = True
        footer = re.search(r"Rev\.\s*([\d.]+)\s*\S?\s*\d{4}-\d{2}-\d{2}\s+(\d+)",
                           " ".join(text.split()))
        if footer:
            out["revision"] = "Rev. " + footer.group(1)
            out["printed_page"] = int(footer.group(2))
        break
    return out


def check() -> dict:
    refs = entries()
    used = cited()
    report = {
        "references": numbering(),
        "cited_but_missing": sorted(set(used) - set(refs)),
        "listed_but_never_cited": sorted(set(refs) - set(used)),
        "entries_without_an_identifier": unresolvable(),
        "bare_citations": bare_citations(),
        "standards_rows_disagreeing": standards_rows_agree(),
        "air_quotation": air_quotation(),
        "citations_per_document": {
            name: sorted({int(t) for g in MARKER.findall(_read(name))
                          for t in g.split(",")})
            for name in CITING_DOCS},
    }
    report["clean"] = (
        report["references"]["contiguous_from_one"]
        and not report["cited_but_missing"]
        and not report["listed_but_never_cited"]
        and not report["entries_without_an_identifier"]
        and not report["bare_citations"]
        and not report["standards_rows_disagreeing"])
    return report


def main() -> int:
    report = check()
    OUT.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n",
                   encoding="utf-8")
    print("references: %d, contiguous: %s"
          % (report["references"]["count"],
             report["references"]["contiguous_from_one"]))
    for key in ("cited_but_missing", "listed_but_never_cited",
                "entries_without_an_identifier", "standards_rows_disagreeing"):
        if report[key]:
            print("  %s: %s" % (key, report[key]))
    for bare in report["bare_citations"]:
        print("  bare citation in %s: %s" % (bare["file"], bare["context"]))
    air = report["air_quotation"]
    print("AIR quotation found: %s, %s printed page %s"
          % (air["quote_found"], air["revision"], air["printed_page"]))
    print("clean: %s" % report["clean"])
    print("wrote %s" % OUT)
    return 0 if report["clean"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
